server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: auth-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-app
          service: auth-backend
          environment: development
          __path__: /app/logs/*.log  # Where our app writes logs
    
    pipeline_stages:
      - json:
          expressions:
            level: level          # Extract log level (info, warn, error)
            timestamp: timestamp  # Extract timestamp
            message: message      # Extract log message
            trace_id: trace_id    # Extract trace ID for correlation
            user_id: user_id      # Extract user ID if present
            
      - labels:
          level:
          
      - timestamp:
          source: timestamp
          format: RFC3339Nano
          
      - output:
          source: message

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
    
    pipeline_stages:
      - match:
          selector: '{job="system"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\S+\s+\S+)\s+(?P<level>\S+)\s+(?P<message>.*)$'
            - labels:
                level:
