global:
  scrape_interval: 15s
  
  evaluation_interval: 15s
  
  external_labels:
    monitor: 'auth-app-monitor'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-app'
    scrape_interval: 10s
    static_configs:
      # If running locally (not in Docker), use host.docker.internal:8080
      # If running in Docker, use the container name
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'auth-backend'
          instance: 'auth-app-1'
    
    metrics_path: '/metrics'
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'

  # Node exporter (optional) - system-level metrics like CPU, memory, disk
  # Uncomment if you want to monitor the host system
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # PostgreSQL exporter (optional) - database metrics
  # Uncomment if you want detailed database monitoring
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
